#!/usr/bin/env python3
"""Independent NF-e/NFC-e 4.00 XSD conformance probe for synthetic fixtures.

Requires lxml and the authentic, SHA-256-pinned PL_010f_v1.04 ZIP.
Does not authenticate the issuer, call SEFAZ or claim fiscal authorization.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import tempfile
import zipfile
from pathlib import Path

PINNED_010F_SHA256 = "b8589490a58a09a993a80e6ac4d7ed10f20892061ecfc56719337098d4b95998"
PACKAGE = "PL_010f_v1.04"
SCHEMAS = (
    "nfe_v4.00.xsd",
    "leiauteNFe_v4.00.xsd",
    "tiposBasico_v4.00.xsd",
    "DFeTiposBasicos_v1.00.xsd",
    "xmldsig-core-schema_v1.01.xsd",
)
NFE = "{http://www.portalfiscal.inf.br/nfe}"
DS = "{http://www.w3.org/2000/09/xmldsig#}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema-zip", required=True, type=Path,
                        help="010f ZIP downloaded directly from the official NF-e portal")
    parser.add_argument("--fixtures-dir", required=True, type=Path,
                        help="synthetic XML generated by TestExportOfficialNFCeSchemaFixtures")
    args = parser.parse_args()

    try:
        from lxml import etree
    except ImportError:
        print("ERRO: instale lxml em ambiente isolado (python -m pip install lxml)", file=sys.stderr)
        return 2

    digest = hashlib.sha256(args.schema_zip.read_bytes()).hexdigest()
    if digest != PINNED_010F_SHA256:
        print(f"FALHA: SHA-256 do pacote oficial inesperado: {digest}", file=sys.stderr)
        print("Não aceite outro ZIP sem auditar e atualizar explicitamente a referência.", file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory(prefix="nfce-official-010f-") as tmp:
        root = Path(tmp)
        with zipfile.ZipFile(args.schema_zip) as archive:
            for schema in SCHEMAS:
                member = f"{PACKAGE}/{schema}"
                if member not in archive.namelist():
                    print(f"FALHA: XSD obrigatório ausente: {member}", file=sys.stderr)
                    return 2
                meta = archive.getinfo(member)
                if meta.file_size > 3_000_000:
                    print(f"FALHA: XSD inesperadamente grande: {member}", file=sys.stderr)
                    return 2
                (root / schema).write_bytes(archive.read(member))
        xml_parser = etree.XMLParser(resolve_entities=False, no_network=True, load_dtd=False)
        schema = etree.XMLSchema(etree.parse(str(root / "nfe_v4.00.xsd"), parser=xml_parser))

        failures = 0
        for profile in ("legacy", "rtc"):
            file_path = args.fixtures_dir / f"nfce-{profile}-signed.xml"
            raw_path = args.fixtures_dir / f"nfce-{profile}-unsigned.xml"
            try:
                doc = etree.parse(str(file_path), parser=xml_parser)
                unsigned = etree.parse(str(raw_path), parser=xml_parser)
            except (OSError, etree.XMLSyntaxError) as exc:
                print(f"FALHA: fixture {profile}: {exc}", file=sys.stderr)
                failures += 1
                continue
            children = [node.tag for node in doc.getroot()]
            expected = [NFE + "infNFe", NFE + "infNFeSupl", DS + "Signature"]
            if doc.getroot().tag != NFE + "NFe" or children != expected:
                print(f"FALHA: posição da assinatura {profile}: {children}", file=sys.stderr)
                failures += 1
                continue
            if not schema.validate(doc):
                print(f"FALHA: NFC-e assinada {profile} NÃO passa XSD 010f:", file=sys.stderr)
                for issue in schema.error_log[:12]:
                    print("  ", issue.message, file=sys.stderr)
                failures += 1
                continue
            if schema.validate(unsigned):
                print(f"FALHA: XSD aceitou documento SEM assinatura ({profile})", file=sys.stderr)
                failures += 1
                continue
            print(f"PASSOU: NFC-e assinada ({profile}) conforme XSD 010f; unsigned corretamente rejeitado")

        if failures:
            return 1
    print("OK: ambas as estruturas XML assinadas passaram. Não houve transmissão à SEFAZ.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
